CS50_Rails_Seminar_EXAMPLE/todo_list_with_items/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  Rails.application.routes.draw do
    
    resources :items
    
    root 'welcome#index'
  end
  

end

CS50_Rails_Seminar_EXAMPLE/todo_list_with_items/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

CS50_Rails_Seminar_EXAMPLE/todo_list_with_items/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
  end
  
  def create
    render plain: params[:item].inspect
  end  
end

CS50_Rails_Seminar_EXAMPLE/todo_list_with_items/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

CS50_Rails_Seminar_EXAMPLE/todo_list_with_items/app/helpers/items_helper.rb
module ItemsHelper
end

CS50_Rails_Seminar_EXAMPLE/todo_list_with_items/app/helpers/welcome_helper.rb
module WelcomeHelper
end

CS50_Rails_Seminar_EXAMPLE/todo_list_with_items/app/views/items/new.html.erb
<h1>New Item</h1>
<%= form_for :item, url: items_path do |f| %>  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

CS50_Rails_Seminar_EXAMPLE/todo_list_with_items/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoListStartingOut</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

CS50_Rails_Seminar_EXAMPLE/todo_list_with_items/app/views/welcome/index.html.erb
<h1>Hello!</h1>