get_static/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'static_pages#home'
    resources :users
end

get_static/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

get_static/app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase }

    validates(:name,  presence: true, length: {maximum: 50})

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates(:email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false})

    has_secure_password
    validates :password, presence: true,  length: { minimum: 6}

    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost

    BCrypt::Password.create(string, cost: cost)
    end
end

get_static/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
        include SessionsHelper
end

get_static/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
         def new
         end

        def create
                user = User.find_by(email: params[:session][:email].downcase)

                if user && user.authenticate(params[:session][:password])
                        log_in user
                        redirect_to user
                else
                        flash[:danger] = 'Invalid email/password combination'
                        render 'new'
                end
        end

        def destroy
                log_out
                redirect_to root_url
        end
end

get_static/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

get_static/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		#debugger
 	 end

	def new
      		@user = User.new
	  end
	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:sucess] = "Welcome to the Sample App!"
			redirect_to @user
		else
			render 'new'
		end
	end
	
	def user_params
		params.require(:user).permit(:name,:email, :password, :password_confirmation)
	end

end

get_static/app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

get_static/app/helpers/sessions_helper.rb
module SessionsHelper
        def log_in(user)
                session[:user_id] = user.id
        end

        def current_user
                @current_user ||= User.find_by(id: session[:user_id])
        end

        def logged_in?
                !current_user.nil?
        end

        def log_out
                session.delete(:user_id)
                @current_user = nil
        end
end

get_static/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

get_static/app/helpers/users_helper.rb
module UsersHelper
        def gravatar_for(user, size: 80)
                gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
                gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=retro&s=#{size}"
                image_tag(gravatar_url, alt:user.name, class: "gravatar")
        end
end

get_static/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.cjoshmartin.com/">Josh Martin</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path    %></li>
      <li><%= link_to "Contact", contact_path  %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

get_static/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",     help_path %></li>
        <% if logged_in? %>
                <li><%= link_to "Users", '#' %></li>
                <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
                        Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                                <li><%= link_to "Profile", current_user %></li>
                                <li><%= link_to "Settings", "#" %></li>
                                <li class="divider"> </li>
                                <li> <%= link_to "Logout", logout_path, method: :delete %> </li>
                       </ul>
                </li>
        <% else %>
                <li><%= link_to "Login", login_path %> </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

get_static/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

get_static/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

   <%= render 'layouts/shim' %>
  </head>
  <body>
   <%= render 'layouts/header' %>
   <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %> </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
</div>
  </body>
</html>