CS50_Rails_Seminar_EXAMPLE/todo_list_final/config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  Rails.application.routes.draw do
    resources :items
    
    root 'welcome#index'
  end

end

CS50_Rails_Seminar_EXAMPLE/todo_list_final/app/models/item.rb
class Item < ActiveRecord::Base
end

CS50_Rails_Seminar_EXAMPLE/todo_list_final/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

CS50_Rails_Seminar_EXAMPLE/todo_list_final/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
 
  def show
    @item = Item.find(params[:id])
  end
 
  def new
    @item = Item.new
  end
 
  def edit
    @item = Item.find(params[:id])
  end
 
  def create
    @item = Item.new(item_params)
 
    if @item.save
      redirect_to @item
    else
      render 'new'
    end
  end
 
  def update
    @item = Item.find(params[:id])
 
    if @item.update(item_params)
      redirect_to @item
    else
      render 'edit'
    end
  end
 
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    
    redirect_to items_path
  end
 
  private
    def item_params
      params.require(:item).permit(:title, :notes)
    end
end

CS50_Rails_Seminar_EXAMPLE/todo_list_final/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

CS50_Rails_Seminar_EXAMPLE/todo_list_final/app/helpers/items_helper.rb
module ItemsHelper
end

CS50_Rails_Seminar_EXAMPLE/todo_list_final/app/helpers/welcome_helper.rb
module WelcomeHelper
end

CS50_Rails_Seminar_EXAMPLE/todo_list_final/app/views/items/edit.html.erb
<h1>Edit Todo Item</h1>
<%= form_for @item do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title%>
  </p>
 
  <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', items_path %>

CS50_Rails_Seminar_EXAMPLE/todo_list_final/app/views/items/index.html.erb
<h1>Todo List</h1>
<%= link_to 'New Todo Item', new_item_path %>
<table>
  <tr>
    <th>Item</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @items.each do |item| %>
    <tr>
      <td><%= item.title %></td>
      <td><%= item.notes %></td>
      <td><%= link_to 'Show', item_path(item) %></td>
      <td><%= link_to 'Edit', edit_item_path(item) %></td>
      <td><%= link_to 'Destroy', item_path(item), method: :delete %></td>
    </tr>
  <% end %>
</table>

CS50_Rails_Seminar_EXAMPLE/todo_list_final/app/views/items/new.html.erb
<h1>New Todo Item</h1>
<%= form_for :item, url: items_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title%>
  </p>
 
  <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', items_path %>

CS50_Rails_Seminar_EXAMPLE/todo_list_final/app/views/items/show.html.erb
<p>
  <strong>Todo:</strong>
  <%= @item.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @item.notes %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back To Todo List', items_path %>

CS50_Rails_Seminar_EXAMPLE/todo_list_final/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>